---
- name: Enable and start docker
  service:
    name: docker
    enabled: yes
    state: restarted

- name: Enable and start kubelet
  service:
    name: kubelet
    enabled: yes
    state: restarted

- name: Reload daemon
  shell: systemctl daemon-reload
  

