apiVersion: v1
kind: Pod
metadata:
  name: wdli-flask
spec:
  volumes:
  - name: "wdli-flask-vol"
    hostPath:
      path: "/opt/k8"      
  containers:
  - image: docker.io/wdlidocker/wdli-flask:2
    name: wdli-flask-docker-img
    volumeMounts:
        - mountPath: "/data"
          name: "wdli-flask-vol"
    livenessProbe:
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
    resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "256Mi"
    ports:
    - containerPort: 5000
      name: http
      protocol: TCP
