#
# K8 setup main playbook
# 

- hosts: all
  become: yes
  vars_files:
    - k8-vars.yaml
  tasks:
  - name: Add DNS entries to host file
    blockinfile:
      path: /etc/hosts
      block: |
        {{master_ip}} {{master_name}}
        {{worker1_ip}} {{worker1_name}}
        {{worker2_ip}} {{worker2_name}}
        
  - name: Disable SElinux
    selinux:
      state: disabled

  - name: Disable swap space
    shell: swapoff -a

  - name: Set up netfilter bridge
    shell: "{{ item }}"
    with_items: 
       - modprobe br_netfilter
       - echo '1' >> /proc/sys/net/bridge/bridge-nf-call-iptables


  - name: Install Docker runtime dependencies
    yum:
      name: "{{item}}"
      state: latest
    with_items:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

  - name: Add Docker repo
    shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    

  - name: Install Docker runtime
    yum:
      name: docker-ce
      state: latest

  - name: Copy K8s repo file
    copy:
      src: kubernetes.repo
      dest: /etc/yum.repos.d/
      owner: root
      group: root
      mode: 0644

  - name: Install K8s components
    yum:
      name: "{{item}}"
      state: latest
    with_items:
      - kubeadm
      - kubectl
      - kubelet
